version: "3"

services:
  payjoin-postgres:
    image: postgres:14.5-bullseye
    volumes:
      - "$APP_SCRIPT_PATH/data/pg:/var/lib/postgresql/data"
      - "$LOGS_DATAPATH:/cnlogs"
    env_file:
      - "$APP_SCRIPT_PATH/data/postgres.env"
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - cyphernodeappsnet
    stop_grace_period: 90s
    deploy:
      replicas: 1
      restart_policy:
        condition: 'any'
        delay: 1s
      update_config:
        parallelism: 1

  payjoin:
    image: cyphernode/payjoin:v0.1.0-local
    build:
      context: .
      target: prod
    volumes:
      - "$APP_SCRIPT_PATH/data://data"
      - "$APP_SCRIPT_PATH/data/config.env:/payjoin/.env"
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/payjoin/cert.pem:ro"
      - "$APP_SCRIPT_PATH/data/logs:/payjoin/logs"
    networks:
      - cyphernodeappsnet

    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.rule=PathPrefixStrip:/payjoin"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.frontend.auth.basic.users=<username>:$$2y$$05$$LFKGjKBkmWbI5RUFBqwonOWEcen4Yu.mU139fvD3flWcP8gUqLLaC"

    depends_on:
      - payjoin-postgres

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=cyphernodeappsnet

        - traefik.http.routers.payjoin.rule=PathPrefix(`/payjoin`)
        - traefik.http.routers.payjoin.entrypoints=websecure
        - traefik.http.routers.payjoin.tls=true
        - traefik.http.routers.payjoin.service=payjoin
        - traefik.http.routers.payjoin.middlewares=payjoin-redirectregex@docker,payjoin-stripprefix@docker,payjoin-auth@docker

        - traefik.http.services.payjoin.loadbalancer.server.port=8000
        - traefik.http.services.payjoin.loadbalancer.passHostHeader=true

        - traefik.http.middlewares.payjoin-redirectregex.redirectregex.regex=^(.*)/payjoin$$
        - traefik.http.middlewares.payjoin-redirectregex.redirectregex.replacement=$$1/payjoin/
        - traefik.http.middlewares.payjoin-redirectregex.redirectregex.permanent=true
        - traefik.http.middlewares.payjoin-stripprefix.stripprefix.prefixes=/payjoin,/payjoin/
        - traefik.http.middlewares.payjoin-auth.basicauth.users=<username>:$$2y$$05$$LFKGjKBkmWbI5RUFBqwonOWEcen4Yu.mU139fvD3flWcP8gUqLLaC
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        condition: "any"
        delay: 1s
      update_config:
        parallelism: 1

networks:
  cyphernodeappsnet:
    external: true
