bitcoind_rpchost="http://bitcoin:18443/wallet/spending06.dat"

bitcoind_rpcuser="cyphernode"

bitcoind_rpcpassword="cyphernode"

port="3002"

pj_endpoint="https://localhost:3002"

pj_directory = "https://payjo.in"

ohttp_relay="https://pj.bobspacebkk.com"
