name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Rewrite SSH GitHub URLs to HTTPS
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install Yarn (required by uniffi-bindgen-react-native prepare script)
        run: npm install -g yarn

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          STUB_MODE: 'true'

  build:
    runs-on: ubuntu-latest

    env:
      APP_SCRIPT_PATH: ${{ github.workspace }}/cypherapps
      GATEKEEPER_DATAPATH: ${{ github.workspace }}/gatekeeper/data
      LOGS_DATAPATH: ${{ github.workspace }}/logs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq docker-compose

      - name: Build Docker Image
        run: docker build -t cyphernode/payjoin:v0.1.0-local .
        shell: bash

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - run: echo "🍏 This job's status is ${{ job.status }}."