name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_SCRIPT_PATH: ${{ github.workspace }}/cypherapps
      GATEKEEPER_DATAPATH: ${{ github.workspace }}/gatekeeper/data
      LOGS_DATAPATH: ${{ github.workspace }}/logs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq docker-compose

      - name: Build Docker Image
        run: docker build -t cyphernode/coinfuser:v0.1.0-local .
        shell: bash

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - run: echo "🍏 This job's status is ${{ job.status }}."